# Generated by Django 4.2.4 on 2023-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("Fashion", "Fashion"),
                    ("Toys", "Toys"),
                    ("Electronics", "Electronics"),
                    ("Home", "Home"),
                ],
                default=1,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
